## Assignment

The operand to the left of the = operator is the name of the variable and the operand to the right of the = operator is the value stored in the variable.
Python allows you to assign a single value to several variables simultaneously

In [58]:
x=5
x

5

In [3]:
a=b=1

In [4]:
a

1

In [5]:
b

1

## Data types






In [32]:
x_int=3

x_float=3.

x_string="three"
type(x_int)

x_list=[3,"three"]


In [28]:
type(x_float)


float

In [29]:
type(x_string)

str

In [33]:
type(x_list)

list

### Numbers

In [64]:
abs(-1)

1

In [67]:
import math

math.floor(4.5)

4.0

In [69]:
math.exp(1)

2.718281828459045

In [71]:
math.log(1)

0.0

In [72]:
math.log10(10)

1.0

In [74]:
math.sqrt(9)

3.0

In [76]:
round(4.54,1)

4.5

### Strings


In [215]:
str = 'Hello World!'
len(str)


12

In [19]:
print(str)          # Prints complete string
print(str[0])       # Prints first character of the string
print(str[2:5])     # Prints characters starting from 3rd to 5th
print(str[2:])      # Prints string starting from 3rd character
print(str[:5])      # Prints string starting from the beginning to 5th
print(str * 2)      # Prints string two times
print(str + "TEST") # Prints concatenated string

Hello World!
H
llo
llo World!
Hello
Hello World!Hello World!
Hello World!TEST


In [20]:
print(str/2)

TypeError: unsupported operand type(s) for /: 'str' and 'int'

In [21]:
print(str -"TEST")

TypeError: unsupported operand type(s) for -: 'str' and 'str'

In [22]:
print(str**2)

TypeError: unsupported operand type(s) for ** or pow(): 'str' and 'int'

Other subsettings

In [34]:
print(str[-1]) #print last character

!


In [35]:
str[-4:-2]#slice starting from the 4th element from the end and stopping before the 2nd element from the end

'rl'

capitalizing strings:

In [191]:
x="test"

In [192]:
x.capitalize()

'Test'

In [196]:
x.find("e")

1

In [212]:
x="TEST"
x.lower()

'test'

In [36]:
x_list[0]

3

### Lists

Lists are the most versatile of Python's compound data types. A list can be of different data types.

In [47]:
x_list

[3, 'three']

In [50]:
x_list.append("III")
x_list

[3, 'three', 'III', 'III']

In [220]:
x_list.append("III")
x_list

[3, 'three', 'III', 'III', 'III', 'III', 'III']

In [222]:
del x_list[-1]
x_list

[3, 'three', 'III', 'III', 'III']

In [37]:
y_list=["john", "2.", "1"]

y_list+x_list

['john', '2.', '1', 3, 'three']

In [39]:
x_list*2

[3, 'three', 3, 'three']

In [81]:
z_list=[4,78,3]
max(z_list)

78

In [82]:
min(z_list)

3

In [116]:
sum(z_list)

85

In [85]:
z_list.count(4)

1

In [88]:
z_list.sort()
z_list

[3, 4, 78]

In [91]:
z_list.reverse()
z_list

[78, 4, 3]

In [98]:
import random
random.random()

0.5742748228224827

### Tuples

Tuples can be thought of as read-only lists.

In [265]:
y_tuple=("john", "2.", "1")
type(y_tuple)

tuple

In [42]:
y_list

['john', '2.', '1']

In [43]:
y_list[0]="Erik"
y_list

['Erik', '2.', '1']

In [46]:
y_tuple[0]="Erik"

TypeError: 'tuple' object does not support item assignment

### Dictionaries

Python's dictionaries are kind of hash table type, where at each key is associated a value without any specific order.

In [266]:
tinydict = {'name': 'john','code':6734, 'dept': 'sales'}
type(tinydict)

dict

In [52]:
print tinydict          # Prints complete dictionary
print tinydict.keys()   # Prints all the keys
print tinydict.values() # Prints all the values

{'dept': 'sales', 'code': 6734, 'name': 'john'}
['dept', 'code', 'name']
['sales', 6734, 'john']


In [267]:
tinydict["code"]

6734

In [268]:
tinydict["surname"]

KeyError: 'surname'

In [270]:
tinydict['dept'] = "R&D"; # update existing entry
tinydict['surname'] = "Sloan"; # Add new entry

In [271]:
tinydict["surname"]

'Sloan'

In [273]:
del tinydict['code']; # remove entry with key 'code'

In [274]:
tinydict["code"]

KeyError: 'code'

In [ ]:
tinydict.clear();     # remove all entries in dict
del tinydict ;        # delete entire dictionary

When duplicate keys encountered during assignment, the last assignment wins

In [2]:
dict = {'Name': 'Zara', 'Age': 7, 'Name': 'Manni'}

In [276]:
dict

{'Age': 7, 'Name': 'Manni'}

The method cmp() compares two dictionaries based on key and values.
This method returns 0 if both dictionaries are equal, -1 if dict1 < dict2 and 1 if dict1 > dic2.

In [277]:
dict1 = {'Name': 'Zara', 'Age': 7};
dict2 = {'Name': 'Mahnaz', 'Age': 27};
dict3 = {'Name': 'Abid', 'Age': 27};
dict4 = {'Name': 'Zara', 'Age': 7};
print "Return Value : %d" %  cmp (dict1, dict2)
print "Return Value : %d" %  cmp (dict2, dict3)
print "Return Value : %d" %  cmp (dict1, dict4)

Return Value : -1
Return Value : 1
Return Value : 0


Finding the total number of items in the dictionary:

In [3]:
len(dict)

2

Produces a printable string representation of a dictionary:

In [4]:
str(dict)

"{'Age': 7, 'Name': 'Manni'}"

### Functions

In [264]:
def mean(mylist):
    "given a list of numerical values calculate the mean of the elements"
    
    denominator=len(mylist)
    numerator=sum(mylist)
    
    return numerator/denominator
    

In [119]:
type(mean)

function

In [121]:
z_list

[78, 4, 3]

In [263]:
mean(z_list)

28

In [123]:
help(mean)

Help on function mean in module __main__:

mean(mylist)
    given a list calculate the mean of the elements



## Loops

In general, statements are executed sequentially: The first statement in a function is executed first, followed by the second, and so on. There may be a situation when you need to execute a block of code several number of times.

Programming languages provide various control structures that allow for more complicated execution paths.

A loop statement allows us to execute a statement or group of statements multiple times.

### `while` loop
 	Repeats a statement or group of statements while a given condition is TRUE. It tests the condition before executing the loop body.

In [23]:
count = 0
while (count < 9):
   print('The count is:', count)
   count = count + 1

print("Good bye!")

('The count is:', 0)
('The count is:', 1)
('The count is:', 2)
('The count is:', 3)
('The count is:', 4)
('The count is:', 5)
('The count is:', 6)
('The count is:', 7)
('The count is:', 8)
Good bye!


A loop becomes infinite loop if a condition never becomes FALSE. You must use caution when using while loops because of the possibility that this condition never resolves to a FALSE value. This results in a loop that never ends. Such a loop is called an infinite loop.

An infinite loop might be useful in client/server programming where the server needs to run continuously so that client programs can communicate with it as and when required.

### `for` loop
Executes a sequence of statements multiple times and abbreviates the code that manages the loop variable.

In [19]:
fruits = ['banana', 'apple',  'mango']
for fruit in fruits:        # Second Example
   print('Current fruit :', fruit)

('Current fruit :', 'banana')
('Current fruit :', 'apple')
('Current fruit :', 'mango')


In [20]:
for index in range(len(fruits)):
   print('Current fruit :', fruits[index])

('Current fruit :', 'banana')
('Current fruit :', 'apple')
('Current fruit :', 'mango')


In [261]:
len(fruits)

3

In [259]:
range(len(fruits))

[0, 1, 2]

### nested loops

Python programming language allows to use one loop inside another loop.
A final note on loop nesting is that you can put any type of loop inside of any other type of loop. For example a for loop can be inside a while loop or vice versa.

In [17]:
for x in range(1, 11):
    for y in range(1, 11):
        print('%d * %d = %d' % (x, y, x*y))

1 * 1 = 1
1 * 2 = 2
1 * 3 = 3
1 * 4 = 4
1 * 5 = 5
1 * 6 = 6
1 * 7 = 7
1 * 8 = 8
1 * 9 = 9
1 * 10 = 10
2 * 1 = 2
2 * 2 = 4
2 * 3 = 6
2 * 4 = 8
2 * 5 = 10
2 * 6 = 12
2 * 7 = 14
2 * 8 = 16
2 * 9 = 18
2 * 10 = 20
3 * 1 = 3
3 * 2 = 6
3 * 3 = 9
3 * 4 = 12
3 * 5 = 15
3 * 6 = 18
3 * 7 = 21
3 * 8 = 24
3 * 9 = 27
3 * 10 = 30
4 * 1 = 4
4 * 2 = 8
4 * 3 = 12
4 * 4 = 16
4 * 5 = 20
4 * 6 = 24
4 * 7 = 28
4 * 8 = 32
4 * 9 = 36
4 * 10 = 40
5 * 1 = 5
5 * 2 = 10
5 * 3 = 15
5 * 4 = 20
5 * 5 = 25
5 * 6 = 30
5 * 7 = 35
5 * 8 = 40
5 * 9 = 45
5 * 10 = 50
6 * 1 = 6
6 * 2 = 12
6 * 3 = 18
6 * 4 = 24
6 * 5 = 30
6 * 6 = 36
6 * 7 = 42
6 * 8 = 48
6 * 9 = 54
6 * 10 = 60
7 * 1 = 7
7 * 2 = 14
7 * 3 = 21
7 * 4 = 28
7 * 5 = 35
7 * 6 = 42
7 * 7 = 49
7 * 8 = 56
7 * 9 = 63
7 * 10 = 70
8 * 1 = 8
8 * 2 = 16
8 * 3 = 24
8 * 4 = 32
8 * 5 = 40
8 * 6 = 48
8 * 7 = 56
8 * 8 = 64
8 * 9 = 72
8 * 10 = 80
9 * 1 = 9
9 * 2 = 18
9 * 3 = 27
9 * 4 = 36
9 * 5 = 45
9 * 6 = 54
9 * 7 = 63
9 * 8 = 72
9 * 9 = 81
9 * 10 = 90
10 * 1 = 10
10 * 2 = 20


### `if` -statements

The if statement will evaluate the code only if a given condition is met (used with logical operator such as `==`, `<`, `>`, `=<`, `=>`, `not`, `is`, `in`, etc.
Optionally we can introduce a `else`statement to execute an alternative code when the condition is not met.

In [13]:
x="Mark"

if x in ["Mark", "Jack", "Mary"]:
    print("present!")
else:
    print("absent!")

present!


In [14]:
x="Tom"

if x in ["Mark", "Jack", "Mary"]:
    print("present!")
else:
    print("absent!")

absent!


We can also use one or more `elif` statements to check multiple expressions for TRUE and execute a block of code as soon as one of the conditions evaluates to TRUE

In [16]:
x="Tom"

if x in ["Mark", "Jack", "Mary"]:
    print("present in list A!")
elif x in ["Tom", "Dick", "Harry"]:
    print("present in list B!")
else:
    print("absent!")

present in list B!


`else` statements can be also use with `while` and `for` loops (the code will be executed in the end)

You can also use nested `if` statements.

### `break` statement

It terminates the current loop and resumes execution at the next statement. The break statement can be used in both while and for loops. If you are using nested loops, the break statement stops the execution of the innermost loop and start executing the next line of code after the block.

In [26]:
var=10
while var > 0:              
   print('Current variable value :', var)
   var = var -1
   if var == 5:
      break

print("Good bye!")

('Current variable value :', 10)
('Current variable value :', 9)
('Current variable value :', 8)
('Current variable value :', 7)
('Current variable value :', 6)
Good bye!


### `continue` statement

The `continue` statement rejects all the remaining statements in the current iteration of the loop and moves the control back to the top of the loop (like a "skip").

The continue statement can be used in both `while` and `for` loops.

In [27]:
for letter in 'Python':     # First Example
   if letter == 'h':
      continue
   print('Current Letter :', letter)


('Current Letter :', 'P')
('Current Letter :', 'y')
('Current Letter :', 't')
('Current Letter :', 'o')
('Current Letter :', 'n')


### `pass` statement

The `pass` statement is a null operation; nothing happens when it executes. The `pass` is also useful in places where your code will eventually go, but has not been written yet

In [28]:
for letter in 'Python': 
   if letter == 'h':
      pass
      print('This is pass block')
   print('Current Letter :', letter)

print("Good bye!")

('Current Letter :', 'P')
('Current Letter :', 'y')
('Current Letter :', 't')
This is pass block
('Current Letter :', 'h')
('Current Letter :', 'o')
('Current Letter :', 'n')
Good bye!


`pass`and `continue`could seem similar but they are not. The printed message "This is pass block", wouldn't have been printed if continue had been used instead. `pass` does nothing, `continue` goes to the next iteration.

In [30]:
for letter in 'Python': 
   if letter == 'h':
      continue
      print('This is pass block')
   print('Current Letter :', letter)

print("Good bye!")

('Current Letter :', 'P')
('Current Letter :', 'y')
('Current Letter :', 't')
('Current Letter :', 'o')
('Current Letter :', 'n')
Good bye!


## Numerical Python (NumPy)

In [101]:
import numpy as np

### Creating Arrays

In [103]:
mylist = [1, 2, 3]
x = np.array(mylist)
x

array([1, 2, 3])

In [104]:
type(x)

numpy.ndarray

multidimensional array:

In [105]:
m = np.array([[7, 8, 9], [10, 11, 12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

Use the shape method to find the dimensions of the array. (rows, columns)

In [106]:
x.shape

(3,)

In [107]:
m.shape

(2, 3)

`ones` and `zeroes` returns a new array of given shape and type, filled with ones  or zeroes, respectively.

In [127]:
array_zeros=np.zeros((3,2))
array_ones=np.ones((3,2))

In [128]:
array_zeros

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [129]:
array_ones

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

`eye` returns a 2-D array with ones on the diagonal and zeros elsewhere.

In [130]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

`diag` extracts a diagonal or constructs a diagonal array.

In [132]:
np.diag(x)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

`arange` returns evenly spaced values within a given interval.

In [133]:
n = np.arange(0, 30, 2) # start at 0 count up by 2, stop before 30
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [134]:
len(n)

15

`linspace` returns evenly spaced numbers over a specified interval.

In [137]:
o = np.linspace(0, 4, 9) # return 9 evenly spaced values from 0 to 4
o

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ])

In [138]:
len(o)

9

`reshape` returns an array with the same data with a new shape.

In [136]:
n = n.reshape(3, 5) # reshape array to be 3x5
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

### Combining array

In [141]:
p = np.ones([2, 3])

In [142]:
p

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

Use `vstack` to stack arrays in sequence vertically (row wise).

In [144]:
np.vstack([p, 2*p])

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 2.,  2.,  2.],
       [ 2.,  2.,  2.]])

Use `hstack` to stack arrays in sequence horizontally (column wise).

In [145]:
np.hstack([p, 2*p])

array([[ 1.,  1.,  1.,  2.,  2.,  2.],
       [ 1.,  1.,  1.,  2.,  2.,  2.]])

In [146]:
r=[4,5,6,7]

In [147]:
r2=r[2:4]

In [149]:
r

[4, 5, 6, 7]

In [150]:
r2

[6, 7]

In [152]:
r2[1]=0

In [153]:
r

[4, 5, 6, 7]

In [154]:
r2

[6, 0]

### Operations
Use +, -, *, / and ** to perform element wise addition, subtraction, multiplication, division and power.

In [158]:
x=np.array([1, 2, 3])
y=np.array([4, 5, 6])
print(x + y)

[5 7 9]


dot product:

In [159]:
x.dot(y) # dot product  1*4 + 2*5 + 3*6

32

#### Transposing

In [160]:
z = np.array([y, y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

In [161]:
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [162]:
z.dtype

dtype('int64')

In [163]:
z = z.astype('f')
z.dtype

dtype('float32')

#### Math Functions


In [164]:
a = np.array([-4, -2, 1, 3, 5])

In [165]:
a.max()

5

In [166]:
a.min()

-4

In [167]:
a.sum()

3

In [168]:
a.mean()

0.59999999999999998

In [169]:
a.std()

3.2619012860600183

`argmax` and `argmin` return the index of the maximum and minimum values in the array.

In [171]:
a.argmax()

4

In [172]:
a.argmin()

0

### Indexing/slicing
Use bracket notation to slice: `array[row, column]`. And use : to select a range of rows or columns

In [177]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

A second : can be used to indicate step-size. array[start:stop:stepsize]

Here we are starting 5th element from the end, and counting backwards by 2 until the beginning of the array is reached.

In [178]:
s[-5::-2]

array([64, 36, 16,  4,  0])

In [175]:
r = np.arange(36)
r.resize((6, 6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [176]:
r[2:5, 1:3]

array([[13, 14],
       [19, 20],
       [25, 26]])

### Conditional indexing

In [179]:
r[r > 30] = 30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

### Copying Data

Be careful with copying and modifying arrays in NumPy!

r2 is a slice of r


In [183]:
r2 = r[:3,:3]
r2


array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [184]:
r2[:] = 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

`r` has also been changed!

In [185]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [186]:
r_copy = r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [188]:
r_copy[:] = 10
print(r_copy)


[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]


In [189]:
print(r)

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


### Iterating Over Arrays

In [224]:
test = np.random.randint(0, 10, (4,3))
test

array([[1, 7, 9],
       [0, 9, 7],
       [8, 5, 8],
       [8, 8, 7]])

iterate by row:

In [225]:
for row in test:
    print(row)

[1 7 9]
[0 9 7]
[8 5 8]
[8 8 7]


In [ ]:
iterate by index

In [226]:
for i in range(len(test)):
    print(test[i])

[1 7 9]
[0 9 7]
[8 5 8]
[8 8 7]


Iterate by row and index:

In [227]:
for i, row in enumerate(test):
    print('row', i, 'is', row)

('row', 0, 'is', array([1, 7, 9]))
('row', 1, 'is', array([0, 9, 7]))
('row', 2, 'is', array([8, 5, 8]))
('row', 3, 'is', array([8, 8, 7]))


Use `zip` to iterate over multiple iterables.

In [230]:
test2 = test**2
test2

array([[ 1, 49, 81],
       [ 0, 81, 49],
       [64, 25, 64],
       [64, 64, 49]])

In [231]:
for i, j in zip(test, test2):
    print(i,'+',j,'=',i+j)

(array([1, 7, 9]), '+', array([ 1, 49, 81]), '=', array([ 2, 56, 90]))
(array([0, 9, 7]), '+', array([ 0, 81, 49]), '=', array([ 0, 90, 56]))
(array([8, 5, 8]), '+', array([64, 25, 64]), '=', array([72, 30, 72]))
(array([8, 8, 7]), '+', array([64, 64, 49]), '=', array([72, 72, 56]))


## PANDA

In [232]:
import pandas as pd

In [235]:
animals = ['Tiger', 'Bear', 'Moose']
pd.Series(animals)


0    Tiger
1     Bear
2    Moose
dtype: object

In [234]:
numbers = [1, 2, 3]
pd.Series(numbers)

0    1
1    2
2    3
dtype: int64

In [241]:
sports = {'Archery': 'Bhutan',
          'Golf': 'Scotland',
          'Sumo': 'Japan',
          'Taekwondo': 'South Korea'}
s = pd.Series(sports)
s

Archery           Bhutan
Golf            Scotland
Sumo               Japan
Taekwondo    South Korea
dtype: object

In [242]:
s = pd.Series(sports, index=['Golf', 'Sumo', 'Hockey'])
s

Golf      Scotland
Sumo         Japan
Hockey         NaN
dtype: object

In [244]:
s = pd.Series(sports)
s

Archery           Bhutan
Golf            Scotland
Sumo               Japan
Taekwondo    South Korea
dtype: object

In [245]:
s.iloc[3]

'South Korea'

In [247]:
s.loc["Taekwondo"]

'South Korea'

In [248]:
s[3]

'South Korea'

In [249]:
#this creates a big series of random numbers
s = pd.Series(np.random.randint(0,1000,10000))
s.head()

0    162
1    222
2    851
3    856
4    397
dtype: int64

In [251]:
original_sports = pd.Series({'Archery': 'Bhutan',
                             'Golf': 'Scotland',
                             'Sumo': 'Japan',
                             'Taekwondo': 'South Korea'})
cricket_loving_countries = pd.Series(['Australia',
                                      'Barbados',
                                      'Pakistan',
                                      'England'], 
                                   index=['Cricket',
                                          'Cricket',
                                          'Cricket',
                                          'Cricket'])
all_countries = original_sports.append(cricket_loving_countries)

In [ ]:
original_sports

In [ ]:
cricket_loving_countries

In [ ]:
all_countries